### ISSUE TITLE
UI Login/Registration

### ISSUE THREAD

**Issue by julianertle** [aufgabe3lab/MaraudersMap#2]
User Interface for the Login and Registration Activities

**Comment by FelixAlexK** [comment]
```[tasklist]
### Tasks
- [ ] 2x Username input field
- [ ] 2x Password input field
- [ ] 1x Password confirmation input field
- [ ] 1x Login button
- [ ] 1x Register button
- [ ] 1x goto registration button
- [ ] 1x go back to login button
```

**Comment by FelixAlexK** [comment]
Login & Register UI done
